blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path('', views.BlogIndexView.as_view(), name='blog-index'),
    path('<slug:cat_slug>/<slug:slug>/', views.DetailedView.as_view(), name='blog-detail'),
    path('<slug:cat_slug>/', views.CategoryListView.as_view(), name='cat-index'),
]

root/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('dashboard/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls')),
]

blog/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from slugify import slugify
from ckeditor.fields import RichTextField


# Create your models here.

class Category(models.Model):
    cat_name = models.CharField(max_length=200)
    cat_slug = models.SlugField(max_length=200, default="", blank=True, unique=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.cat_slug = slugify(self.cat_name)
        super(Category, self).save(*args, **kwargs)
    def __str__(self):
        return self.cat_name

STATUS = (
    (0, "Draft"),
    (1, "Publish"),
	(2, "Future"),
)

class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, default="", blank=True, unique=True)
    category = models.ForeignKey(Category, blank=True, on_delete=models.CASCADE)
    #content = models.TextField()
    content = RichTextField()
    author = models.ForeignKey(User, blank=True, on_delete= models.CASCADE,related_name='blog')
    updated_on = models.DateTimeField(auto_now= True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.created_on <= now
        was_published_recently.admin_order_field = '-created_on'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Yayınlanma?'
    def __str__(self):
        return self.title

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Post, Category

class BlogIndexView(generic.ListView):
    model = Post
    #paginate_by = 12
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class DetailedView(generic.DetailView):
    model = Post
    template_name = "blog/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class CategoryListView(generic.ListView):
    model = Category
    template_name = "blog/cat_index.html"

    def get_context_data(self, **kwargs):
        category  = get_object_or_404(Category, cat_slug=self.kwargs.get('cat_slug'))
        context = super().get_context_data(**kwargs)
        context.update({
            'post_list': Post.objects.order_by('-created_on').filter(category_id=category.id),
        })
        return context

blog/templates/blog/cat_index.html
{% include "blog/header.html" with title=cat.cat_name %}

<h1>Articles</h1>
<ul>
{% for blog in post_list %}
    <li><a class="post" href="{% url 'blog:blog-detail' blog.category.cat_slug blog.slug %}">{{ blog.title }}<span> {{ blog.created_on | date }}</a></li>
{% empty %}
    <li>No articles yet.</li>
{% endfor %}
</ul>

blog/templates/blog/detail.html
{% include "blog/header.html" with title=post.title %}
<h1>{{ post.title }}</h1>
<p>{{ post.content | safe }}</p>
<p>Reporter: {{ post.author }}</p>
<p>Published: {{ post.created_on|date }}</p>
<p>Date: {{ now|date }}</p>

<a class="post" href="{% url 'blog:blog-index' %}">Anasayfa</a>

{% include "blog/footer.html" %}

blog/templates/blog/footer.html
</body>
</html>

blog/templates/blog/header.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>{{title}}</title>
</head>
<body>

blog/templates/blog/index.html
{% include "blog/header.html" with title="Articles" %}
<h1>Articles</h1>
<ul>
{% for blog in object_list %}
    <li><a class="post" href="{% url 'blog:blog-detail' blog.category.cat_slug blog.slug %}">{{ blog.title }}<span> {{ blog.created_on | date }}</a></li>
{% empty %}
    <li>No articles yet.</li>
{% endfor %}
</ul>

{% include "blog/footer.html" %}